### ISSUE TITLE
Load also images from http , not just from local

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/AspNetCoreImageTagHelper#1]
If the image is on local, then opens a reader to read the contents and transform into bytes.
It should be the same with any image on http(s) scheme ;-)

**Comment by davidrevoledo** [comment]
@ignatandrei hope it helps  :) 

https://github.com/ignatandrei/AspNetCoreImageTagHelper/pull/2

**Comment by ignatandrei** [comment]
Thank you!
