### ISSUE TITLE
Improve Code

### ISSUE THREAD

**Issue by davidrevoledo** [ignatandrei/AspNetCoreImageTagHelper#5]
Code factory say we've a D 
https://www.codefactor.io/repository/github/ignatandrei/aspnetcoreimagetaghelper/issues

We should fix those alerts to improve the code and add the badge

**Comment by davidrevoledo** [comment]
Those are from jquery, need to check how to avoid that libary

**Comment by ignatandrei** [comment]
I do not know how is jquery involved...

**Comment by ignatandrei** [comment]
jquery was from the main demo site , not from the library
